# Generated by Django 5.2.1 on 2025-05-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titolo', models.CharField(max_length=100)),
                ('autore', models.CharField(max_length=100)),
                ('anno_pubblicazione', models.IntegerField()),
            ],
        ),
    ]
